FROM ubuntu:16.04


RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y \
      mysql-client \
      php7.0 \
      php7.0-cli \
      php7.0-gd \
      php7.0-intl \
      php7.0-json \
      php7.0-ldap \
      php7.0-mbstring \
      php7.0-mysql \
      php7.0-pgsql \
      php7.0-sqlite3 \
      php7.0-xml \
      php7.0-xsl \
      php7.0-zip \
      php7.0-curl \
      php7.0-soap
